version: 0.0
os: linux
files:
  - source: content
    destination: /tmp
hooks:
  ApplicationStop:
    - location: scripts/kill_container.sh
      timeout: 20
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 60
      runas: ec2-user